/* ============================================================
   Allegiant Attire - catalogue data (extracted from the live
   store: 95 SKUs, real AED prices, MOQs and imagery paths).
   Single place to change the image host if the store moves.
   ============================================================ */
window.AA_IMG_BASE = "https://allegiantattire.store";

window.AA_CATEGORIES = [
  {
    "slug": "t-shirts",
    "label": "T-Shirts",
    "code": "M-01",
    "count": 10,
    "img": "/images/p-tee.jpg",
    "blurb": "180–240 GSM combed cotton crew necks. Blank or printed.",
    "note": "SAME-DAY DTF"
  },
  {
    "slug": "polo-t-shirts",
    "label": "Polo T-Shirts",
    "code": "W-02",
    "count": 10,
    "img": "/images/p-polo.jpg",
    "blurb": "Pique knit polos with ribbed collars for corporate & hospitality.",
    "note": "MOQ 24"
  },
  {
    "slug": "hoodies-sweats",
    "label": "Hoodies & Sweats",
    "code": "C-03",
    "count": 10,
    "img": "/images/p-hoodie.jpg",
    "blurb": "350–400 GSM brushed fleece. Pullover, full-zip, metal zips.",
    "note": "HEAVY FLEECE"
  },
  {
    "slug": "vests-tanks",
    "label": "Vests & Tanks",
    "code": "K-03",
    "count": 10,
    "img": "/images/p-vest.jpg",
    "blurb": "Ribbed tanks & gym vests, cut-and-sew custom fits for teams.",
    "note": "GYM READY"
  },
  {
    "slug": "activewear",
    "label": "Activewear",
    "code": "C-05",
    "count": 10,
    "img": "/images/p-active.jpg",
    "blurb": "Sublimated sets, joggers, leggings, jerseys & tracksuits.",
    "note": "DRY-FIT"
  },
  {
    "slug": "caps",
    "label": "Caps",
    "code": "C-05",
    "count": 10,
    "img": "/images/p-cap.jpg",
    "blurb": "Snapback, trucker & baseball caps, flat or 3D puff embroidery.",
    "note": "3D PUFF"
  },
  {
    "slug": "uniforms",
    "label": "Uniforms",
    "code": "C-07",
    "count": 10,
    "img": "/images/p-uniform.jpg",
    "blurb": "Hotel, hospital, security, school & industrial staff uniforms.",
    "note": "BULK"
  },
  {
    "slug": "school-uniforms",
    "label": "School Uniforms",
    "code": "U-01",
    "count": 5,
    "img": "/images/school-1.webp",
    "blurb": "Term-proof school shirts, pinafores, trousers, PE kits & sweaters.",
    "note": "SCHOOL PROGRAM"
  },
  {
    "slug": "office-uniforms",
    "label": "Office Uniforms",
    "code": "U-02",
    "count": 5,
    "img": "/images/office-1.webp",
    "blurb": "Corporate shirts, blouses, trousers, blazers & waistcoats.",
    "note": "CORPORATE"
  },
  {
    "slug": "construction-uniforms",
    "label": "Construction Uniforms",
    "code": "U-05",
    "count": 5,
    "img": "/images/const-1.webp",
    "blurb": "Hi-vis, coveralls & workwear that survive real sites.",
    "note": "SITE READY"
  },
  {
    "slug": "services",
    "label": "Services",
    "code": "S-01",
    "count": 10,
    "img": "/images/s-dtf.jpg",
    "blurb": "DTF, screen print, sublimation, embroidery, vinyl & labelling.",
    "note": "MOQ 1"
  }
];

window.AA_CATALOG = [
  {
    "id": "t-shirts-01",
    "name": "Classic Crew Tee 01",
    "cat": "t-shirts",
    "catLabel": "T-SHIRTS",
    "price": 29,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 10,
    "badge": "SAME-DAY DTF",
    "desc": "180–240 GSM crew neck. Your artwork in DTF, screen print or embroidery.",
    "img": "/images/tee-2.webp"
  },
  {
    "id": "t-shirts-02",
    "name": "Classic Crew Tee 02",
    "cat": "t-shirts",
    "catLabel": "T-SHIRTS",
    "price": 32,
    "was": 38,
    "rating": 4.7,
    "reviews": 94,
    "moq": 10,
    "badge": "BEST SELLER",
    "desc": "180–240 GSM crew neck. Your artwork in DTF, screen print or embroidery.",
    "img": "/images/tee-3.webp"
  },
  {
    "id": "t-shirts-03",
    "name": "Classic Crew Tee 03",
    "cat": "t-shirts",
    "catLabel": "T-SHIRTS",
    "price": 35,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 10,
    "badge": null,
    "desc": "180–240 GSM crew neck. Your artwork in DTF, screen print or embroidery.",
    "img": "/images/tee-4.webp"
  },
  {
    "id": "t-shirts-04",
    "name": "Classic Crew Tee 04",
    "cat": "t-shirts",
    "catLabel": "T-SHIRTS",
    "price": 26,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 10,
    "badge": null,
    "desc": "180–240 GSM crew neck. Your artwork in DTF, screen print or embroidery.",
    "img": "/images/tee-5.webp"
  },
  {
    "id": "t-shirts-05",
    "name": "Classic Crew Tee 05",
    "cat": "t-shirts",
    "catLabel": "T-SHIRTS",
    "price": 29,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 10,
    "badge": null,
    "desc": "180–240 GSM crew neck. Your artwork in DTF, screen print or embroidery.",
    "img": "/images/tee-1.webp"
  },
  {
    "id": "t-shirts-06",
    "name": "Classic Crew Tee 06",
    "cat": "t-shirts",
    "catLabel": "T-SHIRTS",
    "price": 32,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 10,
    "badge": null,
    "desc": "180–240 GSM crew neck. Your artwork in DTF, screen print or embroidery.",
    "img": "/images/tee-2.webp"
  },
  {
    "id": "t-shirts-07",
    "name": "Classic Crew Tee 07",
    "cat": "t-shirts",
    "catLabel": "T-SHIRTS",
    "price": 35,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 10,
    "badge": null,
    "desc": "180–240 GSM crew neck. Your artwork in DTF, screen print or embroidery.",
    "img": "/images/tee-3.webp"
  },
  {
    "id": "t-shirts-08",
    "name": "Classic Crew Tee 08",
    "cat": "t-shirts",
    "catLabel": "T-SHIRTS",
    "price": 26,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 10,
    "badge": null,
    "desc": "180–240 GSM crew neck. Your artwork in DTF, screen print or embroidery.",
    "img": "/images/tee-4.webp"
  },
  {
    "id": "t-shirts-09",
    "name": "Classic Crew Tee 09",
    "cat": "t-shirts",
    "catLabel": "T-SHIRTS",
    "price": 29,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 10,
    "badge": null,
    "desc": "180–240 GSM crew neck. Your artwork in DTF, screen print or embroidery.",
    "img": "/images/tee-5.webp"
  },
  {
    "id": "t-shirts-10",
    "name": "Classic Crew Tee 10",
    "cat": "t-shirts",
    "catLabel": "T-SHIRTS",
    "price": 32,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 10,
    "badge": null,
    "desc": "180–240 GSM crew neck. Your artwork in DTF, screen print or embroidery.",
    "img": "/images/tee-1.webp"
  },
  {
    "id": "polo-t-shirts-01",
    "name": "Pique Polo Shirt 01",
    "cat": "polo-t-shirts",
    "catLabel": "POLO T-SHIRTS",
    "price": 47,
    "was": 58,
    "rating": 4.6,
    "reviews": 57,
    "moq": 24,
    "badge": "BEST VALUE",
    "desc": "Pique knit polo with ribbed collar. Corporate, hospitality & events favorite.",
    "img": "/images/polo-2.webp"
  },
  {
    "id": "polo-t-shirts-02",
    "name": "Pique Polo Shirt 02",
    "cat": "polo-t-shirts",
    "catLabel": "POLO T-SHIRTS",
    "price": 52,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 24,
    "badge": null,
    "desc": "Pique knit polo with ribbed collar. Corporate, hospitality & events favorite.",
    "img": "/images/polo-3.webp"
  },
  {
    "id": "polo-t-shirts-03",
    "name": "Pique Polo Shirt 03",
    "cat": "polo-t-shirts",
    "catLabel": "POLO T-SHIRTS",
    "price": 57,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 24,
    "badge": null,
    "desc": "Pique knit polo with ribbed collar. Corporate, hospitality & events favorite.",
    "img": "/images/polo-4.webp"
  },
  {
    "id": "polo-t-shirts-04",
    "name": "Pique Polo Shirt 04",
    "cat": "polo-t-shirts",
    "catLabel": "POLO T-SHIRTS",
    "price": 46,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 24,
    "badge": null,
    "desc": "Pique knit polo with ribbed collar. Corporate, hospitality & events favorite.",
    "img": "/images/polo-5.webp"
  },
  {
    "id": "polo-t-shirts-05",
    "name": "Pique Polo Shirt 05",
    "cat": "polo-t-shirts",
    "catLabel": "POLO T-SHIRTS",
    "price": 51,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 24,
    "badge": "WOMEN FIT",
    "desc": "Pique knit polo with ribbed collar. Corporate, hospitality & events favorite.",
    "img": "/images/polo-1.webp"
  },
  {
    "id": "polo-t-shirts-06",
    "name": "Pique Polo Shirt 06",
    "cat": "polo-t-shirts",
    "catLabel": "POLO T-SHIRTS",
    "price": 56,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 24,
    "badge": null,
    "desc": "Pique knit polo with ribbed collar. Corporate, hospitality & events favorite.",
    "img": "/images/polo-2.webp"
  },
  {
    "id": "polo-t-shirts-07",
    "name": "Pique Polo Shirt 07",
    "cat": "polo-t-shirts",
    "catLabel": "POLO T-SHIRTS",
    "price": 45,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 24,
    "badge": null,
    "desc": "Pique knit polo with ribbed collar. Corporate, hospitality & events favorite.",
    "img": "/images/polo-3.webp"
  },
  {
    "id": "polo-t-shirts-08",
    "name": "Pique Polo Shirt 08",
    "cat": "polo-t-shirts",
    "catLabel": "POLO T-SHIRTS",
    "price": 50,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 24,
    "badge": null,
    "desc": "Pique knit polo with ribbed collar. Corporate, hospitality & events favorite.",
    "img": "/images/polo-4.webp"
  },
  {
    "id": "polo-t-shirts-09",
    "name": "Pique Polo Shirt 09",
    "cat": "polo-t-shirts",
    "catLabel": "POLO T-SHIRTS",
    "price": 55,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 24,
    "badge": null,
    "desc": "Pique knit polo with ribbed collar. Corporate, hospitality & events favorite.",
    "img": "/images/polo-5.webp"
  },
  {
    "id": "polo-t-shirts-10",
    "name": "Pique Polo Shirt 10",
    "cat": "polo-t-shirts",
    "catLabel": "POLO T-SHIRTS",
    "price": 44,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 24,
    "badge": null,
    "desc": "Pique knit polo with ribbed collar. Corporate, hospitality & events favorite.",
    "img": "/images/polo-1.webp"
  },
  {
    "id": "hoodies-sweats-01",
    "name": "Fleece Hoodie 01",
    "cat": "hoodies-sweats",
    "catLabel": "HOODIES & SWEATS",
    "price": 89,
    "was": 110,
    "rating": 4.6,
    "reviews": 57,
    "moq": 12,
    "badge": "TOP SELLER",
    "desc": "350–400 GSM brushed fleece. Pullover or full-zip with metal zip.",
    "img": "/images/hoodie-2.webp"
  },
  {
    "id": "hoodies-sweats-02",
    "name": "Fleece Hoodie 02",
    "cat": "hoodies-sweats",
    "catLabel": "HOODIES & SWEATS",
    "price": 96,
    "was": 125,
    "rating": 4.7,
    "reviews": 94,
    "moq": 12,
    "badge": "NEW",
    "desc": "350–400 GSM brushed fleece. Pullover or full-zip with metal zip.",
    "img": "/images/hoodie-3.webp"
  },
  {
    "id": "hoodies-sweats-03",
    "name": "Fleece Hoodie 03",
    "cat": "hoodies-sweats",
    "catLabel": "HOODIES & SWEATS",
    "price": 103,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 12,
    "badge": null,
    "desc": "350–400 GSM brushed fleece. Pullover or full-zip with metal zip.",
    "img": "/images/hoodie-4.webp"
  },
  {
    "id": "hoodies-sweats-04",
    "name": "Fleece Hoodie 04",
    "cat": "hoodies-sweats",
    "catLabel": "HOODIES & SWEATS",
    "price": 86,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 12,
    "badge": null,
    "desc": "350–400 GSM brushed fleece. Pullover or full-zip with metal zip.",
    "img": "/images/hoodie-5.webp"
  },
  {
    "id": "hoodies-sweats-05",
    "name": "Fleece Hoodie 05",
    "cat": "hoodies-sweats",
    "catLabel": "HOODIES & SWEATS",
    "price": 93,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 12,
    "badge": null,
    "desc": "350–400 GSM brushed fleece. Pullover or full-zip with metal zip.",
    "img": "/images/hoodie-1.webp"
  },
  {
    "id": "hoodies-sweats-06",
    "name": "Fleece Hoodie 06",
    "cat": "hoodies-sweats",
    "catLabel": "HOODIES & SWEATS",
    "price": 100,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 12,
    "badge": null,
    "desc": "350–400 GSM brushed fleece. Pullover or full-zip with metal zip.",
    "img": "/images/hoodie-2.webp"
  },
  {
    "id": "hoodies-sweats-07",
    "name": "Fleece Hoodie 07",
    "cat": "hoodies-sweats",
    "catLabel": "HOODIES & SWEATS",
    "price": 83,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 12,
    "badge": null,
    "desc": "350–400 GSM brushed fleece. Pullover or full-zip with metal zip.",
    "img": "/images/hoodie-3.webp"
  },
  {
    "id": "hoodies-sweats-08",
    "name": "Fleece Hoodie 08",
    "cat": "hoodies-sweats",
    "catLabel": "HOODIES & SWEATS",
    "price": 90,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 12,
    "badge": null,
    "desc": "350–400 GSM brushed fleece. Pullover or full-zip with metal zip.",
    "img": "/images/hoodie-4.webp"
  },
  {
    "id": "hoodies-sweats-09",
    "name": "Fleece Hoodie 09",
    "cat": "hoodies-sweats",
    "catLabel": "HOODIES & SWEATS",
    "price": 97,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 12,
    "badge": null,
    "desc": "350–400 GSM brushed fleece. Pullover or full-zip with metal zip.",
    "img": "/images/hoodie-5.webp"
  },
  {
    "id": "hoodies-sweats-10",
    "name": "Fleece Hoodie 10",
    "cat": "hoodies-sweats",
    "catLabel": "HOODIES & SWEATS",
    "price": 104,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 12,
    "badge": null,
    "desc": "350–400 GSM brushed fleece. Pullover or full-zip with metal zip.",
    "img": "/images/hoodie-1.webp"
  },
  {
    "id": "vests-tanks-01",
    "name": "Gym Vest Tank 01",
    "cat": "vests-tanks",
    "catLabel": "VESTS & TANKS",
    "price": 26,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 24,
    "badge": "GYM READY",
    "desc": "Ribbed tanks & gym vests. Cut-and-sew custom fits for teams.",
    "img": "/images/vest-2.webp"
  },
  {
    "id": "vests-tanks-02",
    "name": "Gym Vest Tank 02",
    "cat": "vests-tanks",
    "catLabel": "VESTS & TANKS",
    "price": 28,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 24,
    "badge": null,
    "desc": "Ribbed tanks & gym vests. Cut-and-sew custom fits for teams.",
    "img": "/images/vest-3.webp"
  },
  {
    "id": "vests-tanks-03",
    "name": "Gym Vest Tank 03",
    "cat": "vests-tanks",
    "catLabel": "VESTS & TANKS",
    "price": 30,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 24,
    "badge": null,
    "desc": "Ribbed tanks & gym vests. Cut-and-sew custom fits for teams.",
    "img": "/images/vest-4.webp"
  },
  {
    "id": "vests-tanks-04",
    "name": "Gym Vest Tank 04",
    "cat": "vests-tanks",
    "catLabel": "VESTS & TANKS",
    "price": 32,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 24,
    "badge": null,
    "desc": "Ribbed tanks & gym vests. Cut-and-sew custom fits for teams.",
    "img": "/images/vest-5.webp"
  },
  {
    "id": "vests-tanks-05",
    "name": "Gym Vest Tank 05",
    "cat": "vests-tanks",
    "catLabel": "VESTS & TANKS",
    "price": 24,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 24,
    "badge": null,
    "desc": "Ribbed tanks & gym vests. Cut-and-sew custom fits for teams.",
    "img": "/images/vest-1.webp"
  },
  {
    "id": "vests-tanks-06",
    "name": "Gym Vest Tank 06",
    "cat": "vests-tanks",
    "catLabel": "VESTS & TANKS",
    "price": 26,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 24,
    "badge": null,
    "desc": "Ribbed tanks & gym vests. Cut-and-sew custom fits for teams.",
    "img": "/images/vest-2.webp"
  },
  {
    "id": "vests-tanks-07",
    "name": "Gym Vest Tank 07",
    "cat": "vests-tanks",
    "catLabel": "VESTS & TANKS",
    "price": 28,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 24,
    "badge": null,
    "desc": "Ribbed tanks & gym vests. Cut-and-sew custom fits for teams.",
    "img": "/images/vest-3.webp"
  },
  {
    "id": "vests-tanks-08",
    "name": "Gym Vest Tank 08",
    "cat": "vests-tanks",
    "catLabel": "VESTS & TANKS",
    "price": 30,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 24,
    "badge": null,
    "desc": "Ribbed tanks & gym vests. Cut-and-sew custom fits for teams.",
    "img": "/images/vest-4.webp"
  },
  {
    "id": "vests-tanks-09",
    "name": "Gym Vest Tank 09",
    "cat": "vests-tanks",
    "catLabel": "VESTS & TANKS",
    "price": 32,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 24,
    "badge": null,
    "desc": "Ribbed tanks & gym vests. Cut-and-sew custom fits for teams.",
    "img": "/images/vest-5.webp"
  },
  {
    "id": "vests-tanks-10",
    "name": "Gym Vest Tank 10",
    "cat": "vests-tanks",
    "catLabel": "VESTS & TANKS",
    "price": 24,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 24,
    "badge": null,
    "desc": "Ribbed tanks & gym vests. Cut-and-sew custom fits for teams.",
    "img": "/images/vest-1.webp"
  },
  {
    "id": "activewear-01",
    "name": "Activewear Set 01",
    "cat": "activewear",
    "catLabel": "ACTIVEWEAR",
    "price": 94,
    "was": 120,
    "rating": 4.6,
    "reviews": 57,
    "moq": 20,
    "badge": "DRY-FIT",
    "desc": "Sublimated gym & team wear. Joggers, leggings, jerseys, tracksuits.",
    "img": "/images/active-2.webp"
  },
  {
    "id": "activewear-02",
    "name": "Activewear Set 02",
    "cat": "activewear",
    "catLabel": "ACTIVEWEAR",
    "price": 100,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 20,
    "badge": null,
    "desc": "Sublimated gym & team wear. Joggers, leggings, jerseys, tracksuits.",
    "img": "/images/active-3.webp"
  },
  {
    "id": "activewear-03",
    "name": "Activewear Set 03",
    "cat": "activewear",
    "catLabel": "ACTIVEWEAR",
    "price": 106,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 20,
    "badge": null,
    "desc": "Sublimated gym & team wear. Joggers, leggings, jerseys, tracksuits.",
    "img": "/images/active-4.webp"
  },
  {
    "id": "activewear-04",
    "name": "Activewear Set 04",
    "cat": "activewear",
    "catLabel": "ACTIVEWEAR",
    "price": 112,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 20,
    "badge": null,
    "desc": "Sublimated gym & team wear. Joggers, leggings, jerseys, tracksuits.",
    "img": "/images/active-5.webp"
  },
  {
    "id": "activewear-05",
    "name": "Activewear Set 05",
    "cat": "activewear",
    "catLabel": "ACTIVEWEAR",
    "price": 92,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 20,
    "badge": null,
    "desc": "Sublimated gym & team wear. Joggers, leggings, jerseys, tracksuits.",
    "img": "/images/active-6.webp"
  },
  {
    "id": "activewear-06",
    "name": "Activewear Set 06",
    "cat": "activewear",
    "catLabel": "ACTIVEWEAR",
    "price": 98,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 20,
    "badge": null,
    "desc": "Sublimated gym & team wear. Joggers, leggings, jerseys, tracksuits.",
    "img": "/images/active-7.webp"
  },
  {
    "id": "activewear-07",
    "name": "Activewear Set 07",
    "cat": "activewear",
    "catLabel": "ACTIVEWEAR",
    "price": 104,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 20,
    "badge": null,
    "desc": "Sublimated gym & team wear. Joggers, leggings, jerseys, tracksuits.",
    "img": "/images/active-8.webp"
  },
  {
    "id": "activewear-08",
    "name": "Activewear Set 08",
    "cat": "activewear",
    "catLabel": "ACTIVEWEAR",
    "price": 110,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 20,
    "badge": null,
    "desc": "Sublimated gym & team wear. Joggers, leggings, jerseys, tracksuits.",
    "img": "/images/active-9.webp"
  },
  {
    "id": "activewear-09",
    "name": "Activewear Set 09",
    "cat": "activewear",
    "catLabel": "ACTIVEWEAR",
    "price": 90,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 20,
    "badge": null,
    "desc": "Sublimated gym & team wear. Joggers, leggings, jerseys, tracksuits.",
    "img": "/images/active-10.webp"
  },
  {
    "id": "activewear-10",
    "name": "Activewear Set 10",
    "cat": "activewear",
    "catLabel": "ACTIVEWEAR",
    "price": 96,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 20,
    "badge": null,
    "desc": "Sublimated gym & team wear. Joggers, leggings, jerseys, tracksuits.",
    "img": "/images/active-1.webp"
  },
  {
    "id": "caps-01",
    "name": "Embroidered Cap 01",
    "cat": "caps",
    "catLabel": "CAPS",
    "price": 33,
    "was": 42,
    "rating": 4.6,
    "reviews": 57,
    "moq": 24,
    "badge": "3D PUFF",
    "desc": "Snapback, trucker & baseball caps with flat or 3D puff embroidery.",
    "img": "/images/cap-2.webp"
  },
  {
    "id": "caps-02",
    "name": "Embroidered Cap 02",
    "cat": "caps",
    "catLabel": "CAPS",
    "price": 36,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 24,
    "badge": null,
    "desc": "Snapback, trucker & baseball caps with flat or 3D puff embroidery.",
    "img": "/images/cap-3.webp"
  },
  {
    "id": "caps-03",
    "name": "Embroidered Cap 03",
    "cat": "caps",
    "catLabel": "CAPS",
    "price": 39,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 24,
    "badge": null,
    "desc": "Snapback, trucker & baseball caps with flat or 3D puff embroidery.",
    "img": "/images/cap-4.webp"
  },
  {
    "id": "caps-04",
    "name": "Embroidered Cap 04",
    "cat": "caps",
    "catLabel": "CAPS",
    "price": 30,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 24,
    "badge": null,
    "desc": "Snapback, trucker & baseball caps with flat or 3D puff embroidery.",
    "img": "/images/cap-5.webp"
  },
  {
    "id": "caps-05",
    "name": "Embroidered Cap 05",
    "cat": "caps",
    "catLabel": "CAPS",
    "price": 33,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 24,
    "badge": null,
    "desc": "Snapback, trucker & baseball caps with flat or 3D puff embroidery.",
    "img": "/images/cap-1.webp"
  },
  {
    "id": "caps-06",
    "name": "Embroidered Cap 06",
    "cat": "caps",
    "catLabel": "CAPS",
    "price": 36,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 24,
    "badge": null,
    "desc": "Snapback, trucker & baseball caps with flat or 3D puff embroidery.",
    "img": "/images/cap-2.webp"
  },
  {
    "id": "caps-07",
    "name": "Embroidered Cap 07",
    "cat": "caps",
    "catLabel": "CAPS",
    "price": 39,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 24,
    "badge": null,
    "desc": "Snapback, trucker & baseball caps with flat or 3D puff embroidery.",
    "img": "/images/cap-3.webp"
  },
  {
    "id": "caps-08",
    "name": "Embroidered Cap 08",
    "cat": "caps",
    "catLabel": "CAPS",
    "price": 30,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 24,
    "badge": null,
    "desc": "Snapback, trucker & baseball caps with flat or 3D puff embroidery.",
    "img": "/images/cap-4.webp"
  },
  {
    "id": "caps-09",
    "name": "Embroidered Cap 09",
    "cat": "caps",
    "catLabel": "CAPS",
    "price": 33,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 24,
    "badge": null,
    "desc": "Snapback, trucker & baseball caps with flat or 3D puff embroidery.",
    "img": "/images/cap-5.webp"
  },
  {
    "id": "caps-10",
    "name": "Embroidered Cap 10",
    "cat": "caps",
    "catLabel": "CAPS",
    "price": 36,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 24,
    "badge": null,
    "desc": "Snapback, trucker & baseball caps with flat or 3D puff embroidery.",
    "img": "/images/cap-1.webp"
  },
  {
    "id": "uniforms-01",
    "name": "Staff Uniform 01",
    "cat": "uniforms",
    "catLabel": "UNIFORMS",
    "price": 66,
    "was": 82,
    "rating": 4.6,
    "reviews": 57,
    "moq": 50,
    "badge": "BULK",
    "desc": "Hotel, hospital, security, school & industrial uniforms with logo program.",
    "img": "/images/p-uniform.webp"
  },
  {
    "id": "uniforms-02",
    "name": "Staff Uniform 02",
    "cat": "uniforms",
    "catLabel": "UNIFORMS",
    "price": 74,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 50,
    "badge": null,
    "desc": "Hotel, hospital, security, school & industrial uniforms with logo program.",
    "img": "/images/p-uniform.webp"
  },
  {
    "id": "uniforms-03",
    "name": "Staff Uniform 03",
    "cat": "uniforms",
    "catLabel": "UNIFORMS",
    "price": 82,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 50,
    "badge": null,
    "desc": "Hotel, hospital, security, school & industrial uniforms with logo program.",
    "img": "/images/p-uniform.webp"
  },
  {
    "id": "uniforms-04",
    "name": "Staff Uniform 04",
    "cat": "uniforms",
    "catLabel": "UNIFORMS",
    "price": 60,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 50,
    "badge": null,
    "desc": "Hotel, hospital, security, school & industrial uniforms with logo program.",
    "img": "/images/p-uniform.webp"
  },
  {
    "id": "uniforms-05",
    "name": "Staff Uniform 05",
    "cat": "uniforms",
    "catLabel": "UNIFORMS",
    "price": 68,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 50,
    "badge": null,
    "desc": "Hotel, hospital, security, school & industrial uniforms with logo program.",
    "img": "/images/p-uniform.webp"
  },
  {
    "id": "uniforms-06",
    "name": "Staff Uniform 06",
    "cat": "uniforms",
    "catLabel": "UNIFORMS",
    "price": 76,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 50,
    "badge": null,
    "desc": "Hotel, hospital, security, school & industrial uniforms with logo program.",
    "img": "/images/p-uniform.webp"
  },
  {
    "id": "uniforms-07",
    "name": "Staff Uniform 07",
    "cat": "uniforms",
    "catLabel": "UNIFORMS",
    "price": 84,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 50,
    "badge": null,
    "desc": "Hotel, hospital, security, school & industrial uniforms with logo program.",
    "img": "/images/p-uniform.webp"
  },
  {
    "id": "uniforms-08",
    "name": "Staff Uniform 08",
    "cat": "uniforms",
    "catLabel": "UNIFORMS",
    "price": 62,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 50,
    "badge": null,
    "desc": "Hotel, hospital, security, school & industrial uniforms with logo program.",
    "img": "/images/p-uniform.webp"
  },
  {
    "id": "uniforms-09",
    "name": "Staff Uniform 09",
    "cat": "uniforms",
    "catLabel": "UNIFORMS",
    "price": 70,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 50,
    "badge": null,
    "desc": "Hotel, hospital, security, school & industrial uniforms with logo program.",
    "img": "/images/p-uniform.webp"
  },
  {
    "id": "uniforms-10",
    "name": "Staff Uniform 10",
    "cat": "uniforms",
    "catLabel": "UNIFORMS",
    "price": 78,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 50,
    "badge": null,
    "desc": "Hotel, hospital, security, school & industrial uniforms with logo program.",
    "img": "/images/p-uniform.webp"
  },
  {
    "id": "school-uniforms-01",
    "name": "Classic School Shirt 01",
    "cat": "school-uniforms",
    "catLabel": "SCHOOL UNIFORMS",
    "price": 38,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 50,
    "badge": "BEST SELLER",
    "desc": "Crisp easy-iron school shirt in breathable poly-cotton. Reinforced collar stays sharp all term.",
    "img": "/images/school-1.webp"
  },
  {
    "id": "school-uniforms-02",
    "name": "Girls Pinafore Dress 02",
    "cat": "school-uniforms",
    "catLabel": "SCHOOL UNIFORMS",
    "price": 46,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 50,
    "badge": null,
    "desc": "Durable navy pinafore with side buttons and stain-resistant finish. Machine washable, term after term.",
    "img": "/images/school-2.webp"
  },
  {
    "id": "school-uniforms-03",
    "name": "Boys School Trousers 03",
    "cat": "school-uniforms",
    "catLabel": "SCHOOL UNIFORMS",
    "price": 42,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 50,
    "badge": null,
    "desc": "Comfort-fit grey school trousers with elastic back waist, side pockets and reinforced knees.",
    "img": "/images/school-3.webp"
  },
  {
    "id": "school-uniforms-04",
    "name": "School PE Kit 04",
    "cat": "school-uniforms",
    "catLabel": "SCHOOL UNIFORMS",
    "price": 36,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 50,
    "badge": "NEW",
    "desc": "Two-piece PE kit: breathable white tee with navy shorts. Lightweight and quick-dry for sports day.",
    "img": "/images/school-4.webp"
  },
  {
    "id": "school-uniforms-05",
    "name": "V-Neck School Sweater 05",
    "cat": "school-uniforms",
    "catLabel": "SCHOOL UNIFORMS",
    "price": 48,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 50,
    "badge": null,
    "desc": "Classic V-neck school sweater in soft acrylic knit. Ribbed cuffs and hem hold shape wash after wash.",
    "img": "/images/school-5.webp"
  },
  {
    "id": "office-uniforms-01",
    "name": "Corporate Formal Shirt 01",
    "cat": "office-uniforms",
    "catLabel": "OFFICE UNIFORMS",
    "price": 58,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 24,
    "badge": "NEW",
    "desc": "Premium corporate dress shirt in wrinkle-resistant cotton blend. Sharp collar and button cuffs.",
    "img": "/images/office-1.webp"
  },
  {
    "id": "office-uniforms-02",
    "name": "Ladies Office Blouse 02",
    "cat": "office-uniforms",
    "catLabel": "OFFICE UNIFORMS",
    "price": 62,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 24,
    "badge": null,
    "desc": "Elegant tailored blouse with 3/4 sleeves in wrinkle-free fabric. Polished from office to evening.",
    "img": "/images/office-2.webp"
  },
  {
    "id": "office-uniforms-03",
    "name": "Formal Office Trousers 03",
    "cat": "office-uniforms",
    "catLabel": "OFFICE UNIFORMS",
    "price": 68,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 24,
    "badge": null,
    "desc": "Flat-front formal trousers with belt loops and tapered leg. Crease-resistant all-day fabric.",
    "img": "/images/office-3.webp"
  },
  {
    "id": "office-uniforms-04",
    "name": "Corporate Blazer 04",
    "cat": "office-uniforms",
    "catLabel": "OFFICE UNIFORMS",
    "price": 120,
    "was": 145,
    "rating": 4.9,
    "reviews": 168,
    "moq": 12,
    "badge": "PREMIUM",
    "desc": "Single-breasted corporate blazer with notch lapels and two-button closure. Half-canvassed chest.",
    "img": "/images/office-4.webp"
  },
  {
    "id": "office-uniforms-05",
    "name": "Office Waistcoat 05",
    "cat": "office-uniforms",
    "catLabel": "OFFICE UNIFORMS",
    "price": 54,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 24,
    "badge": null,
    "desc": "Five-button formal waistcoat with adjustable back strap. The finishing layer for front-desk teams.",
    "img": "/images/office-5.webp"
  },
  {
    "id": "construction-uniforms-01",
    "name": "Hi-Vis Safety Vest 01",
    "cat": "construction-uniforms",
    "catLabel": "CONSTRUCTION UNIFORMS",
    "price": 28,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 50,
    "badge": "BEST SELLER",
    "desc": "Class-2 hi-vis vest in neon mesh with silver reflective tape. Lightweight, breathable, site-compliant.",
    "img": "/images/const-1.webp"
  },
  {
    "id": "construction-uniforms-02",
    "name": "Work Coverall Suit 02",
    "cat": "construction-uniforms",
    "catLabel": "CONSTRUCTION UNIFORMS",
    "price": 58,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 24,
    "badge": null,
    "desc": "Heavy-duty coverall with front zip, chest pockets and elastic back waist. Built for tough site days.",
    "img": "/images/const-2.webp"
  },
  {
    "id": "construction-uniforms-03",
    "name": "Cargo Work Trousers 03",
    "cat": "construction-uniforms",
    "catLabel": "CONSTRUCTION UNIFORMS",
    "price": 52,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 24,
    "badge": null,
    "desc": "Ripstop cargo trousers with 6 utility pockets and reinforced knees. Comfort fit for all-day wear.",
    "img": "/images/const-3.webp"
  },
  {
    "id": "construction-uniforms-04",
    "name": "Long-Sleeve Work Shirt 04",
    "cat": "construction-uniforms",
    "catLabel": "CONSTRUCTION UNIFORMS",
    "price": 44,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 24,
    "badge": "NEW",
    "desc": "Long-sleeve work shirt with button cuffs and chest pockets. Fade-resistant, wash-and-wear.",
    "img": "/images/const-4.webp"
  },
  {
    "id": "construction-uniforms-05",
    "name": "Hi-Vis Winter Jacket 05",
    "cat": "construction-uniforms",
    "catLabel": "CONSTRUCTION UNIFORMS",
    "price": 95,
    "was": 115,
    "rating": 5.0,
    "reviews": 205,
    "moq": 24,
    "badge": "PREMIUM",
    "desc": "Padded hi-vis winter jacket with fleece lining and storm cuffs. Warmth plus 360-degree visibility.",
    "img": "/images/const-5.webp"
  },
  {
    "id": "services-01",
    "name": "Print Service Pack 01",
    "cat": "services",
    "catLabel": "SERVICES",
    "price": 19,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 1,
    "badge": "IN-HOUSE",
    "desc": "In-house print & stitch service. DTF, screen, sublimation, embroidery.",
    "img": "/images/s-dtf.webp"
  },
  {
    "id": "services-02",
    "name": "Print Service Pack 02",
    "cat": "services",
    "catLabel": "SERVICES",
    "price": 23,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 1,
    "badge": null,
    "desc": "In-house print & stitch service. DTF, screen, sublimation, embroidery.",
    "img": "/images/s-factory.webp"
  },
  {
    "id": "services-03",
    "name": "Print Service Pack 03",
    "cat": "services",
    "catLabel": "SERVICES",
    "price": 27,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 1,
    "badge": null,
    "desc": "In-house print & stitch service. DTF, screen, sublimation, embroidery.",
    "img": "/images/p-tee.webp"
  },
  {
    "id": "services-04",
    "name": "Print Service Pack 04",
    "cat": "services",
    "catLabel": "SERVICES",
    "price": 31,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 1,
    "badge": null,
    "desc": "In-house print & stitch service. DTF, screen, sublimation, embroidery.",
    "img": "/images/s-dtf.webp"
  },
  {
    "id": "services-05",
    "name": "Print Service Pack 05",
    "cat": "services",
    "catLabel": "SERVICES",
    "price": 15,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 1,
    "badge": null,
    "desc": "In-house print & stitch service. DTF, screen, sublimation, embroidery.",
    "img": "/images/s-factory.webp"
  },
  {
    "id": "services-06",
    "name": "Print Service Pack 06",
    "cat": "services",
    "catLabel": "SERVICES",
    "price": 19,
    "was": null,
    "rating": 4.6,
    "reviews": 57,
    "moq": 1,
    "badge": null,
    "desc": "In-house print & stitch service. DTF, screen, sublimation, embroidery.",
    "img": "/images/p-tee.webp"
  },
  {
    "id": "services-07",
    "name": "Print Service Pack 07",
    "cat": "services",
    "catLabel": "SERVICES",
    "price": 23,
    "was": null,
    "rating": 4.7,
    "reviews": 94,
    "moq": 1,
    "badge": null,
    "desc": "In-house print & stitch service. DTF, screen, sublimation, embroidery.",
    "img": "/images/s-dtf.webp"
  },
  {
    "id": "services-08",
    "name": "Print Service Pack 08",
    "cat": "services",
    "catLabel": "SERVICES",
    "price": 27,
    "was": null,
    "rating": 4.8,
    "reviews": 131,
    "moq": 1,
    "badge": null,
    "desc": "In-house print & stitch service. DTF, screen, sublimation, embroidery.",
    "img": "/images/s-factory.webp"
  },
  {
    "id": "services-09",
    "name": "Print Service Pack 09",
    "cat": "services",
    "catLabel": "SERVICES",
    "price": 31,
    "was": null,
    "rating": 4.9,
    "reviews": 168,
    "moq": 1,
    "badge": null,
    "desc": "In-house print & stitch service. DTF, screen, sublimation, embroidery.",
    "img": "/images/p-tee.webp"
  },
  {
    "id": "services-10",
    "name": "Print Service Pack 10",
    "cat": "services",
    "catLabel": "SERVICES",
    "price": 15,
    "was": null,
    "rating": 5.0,
    "reviews": 205,
    "moq": 1,
    "badge": null,
    "desc": "In-house print & stitch service. DTF, screen, sublimation, embroidery.",
    "img": "/images/s-dtf.webp"
  }
];
