#!/usr/bin/env python3
"""Sync assets/garments/garments.json into the AA_ART block at the end of catalog.js."""
import json, re, os

CAT_ART = {
    "t-shirts": "tee", "polo-t-shirts": "polo", "hoodies-sweats": "hoodie",
    "vests-tanks": "tank", "activewear": "active",
    "caps": "cap", "uniforms": "coverall", "school-uniforms": "shirt",
    "office-uniforms": "shirt", "construction-uniforms": "coverall",
}

with open("assets/garments/garments.json") as fh:
    man = json.load(fh)

art = {}
for slug, gtype in CAT_ART.items():
    set_ = man.get(gtype)
    if not set_ or not set_.get("side") or not set_.get("front"):
        continue
    art[slug] = {"type": gtype, "side": set_["side"], "front": set_["front"]}

block = ("\n/* Rail artwork — background-free garment cut-outs (side + front pairs)\n"
         "   generated by tools/build-garments.py, mapped by tools/build-art-map.py. */\n"
         "window.AA_ART = " + json.dumps(art, indent=2) + ";\n")

src = open("catalog.js", encoding="utf-8").read()
src = re.sub(r"\n/\* Rail artwork.*$", "", src, flags=re.S).rstrip() + "\n" + block
open("catalog.js", "w", encoding="utf-8").write(src)
print("AA_ART categories:", ", ".join(f"{k} ({len(v['side'])} sides / {len(v['front'])} fronts)" for k, v in art.items()))
